booru/account/urls.py
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path('login/', views.LoginView.as_view(), name="login"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('logout/', views.LogoutView.as_view(), name="logout"),
    path('settings/', views.SettingsView.as_view(), name="settings"),
]

booru/core/urls.py
from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path('terms_of_service/', views.TermsOfServiceView.as_view(), name="terms_of_service"),
    path('privacy_policy/', views.PrivacyPolicyView.as_view(), name="privacy_policy"),
    path('staff_page/hash_ban/', views.BannedHashCreateView.as_view(), name="hash_ban"),
    path('staff_page/hash_ban/<int:pk>/delete', views.BannedHashDeleteView.as_view(), name="hash_ban_delete"),
    path('staff_page/mod_queue/', views.ModQueueView.as_view(), name="mod_queue"),
    path('staff_page/mod_queue/<int:pk>/resolve', views.StaffPostFlagResolveView.as_view(), name="mod_queue_resolve"),
]

booru/urls.py
from django.urls import include, path, re_path

import booru.account.views
import booru.core.views

from . import views

app_name = "booru"

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
    re_path(r'^upload/$', views.upload, name='upload'),

    re_path(r'^post/view/(?P<post_id>[0-9]+)/$', views.post_detail, name='post_detail'),
    re_path(r'^post/view/(?P<post_id>[0-9]+)/history$', views.post_history, name='post_history'),
    re_path(r'^post/view/(?P<post_id>[0-9]+)/history/(?P<page_number>[0-9]+)/$', views.post_history, name='post_history'),
    re_path(r'^post/view/(?P<post_id>[0-9]+)/approve$', views.post_approve, name='post_approve'),
    re_path(r'^post/view/(?P<post_id>[0-9]+)/hide$', views.post_hide, name='post_hide'),
    re_path(r'^post/view/(?P<post_id>[0-9]+)/delete$', views.post_delete, name='post_delete'),
    re_path('post/view/(?P<post_id>[0-9]+)/nuke', views.post_nuke, name='post_nuke'),
    re_path(r'^post/view/(?P<post_id>[0-9]+)/favorite$', views.post_favorite, name='post_favorite'),
    re_path(r'^post/view/(?P<post_id>[0-9]+)/vote$', views.post_score_vote, name='post_score_vote'),
    re_path(r'^post/view/(?P<post_id>[0-9]+)/flag$', booru.core.views.PostFlagCreateView.as_view(), name='post_flag'),

    re_path(r'^post/list/$', views.post_list_detail, name='posts'),
    re_path(r'^post/list/(?P<page_number>[0-9]+)/$', views.post_list_detail, name='post_page_detail'),
    
    re_path(r'^tags/$', views.tags_list, name='tags_list'),
    re_path(r'^tags/(?P<tag_id>[0-9]+)/$', views.tag_detail, name='tag_detail'),
    re_path(r'^tags/list/(?P<page_number>[0-9]+)/$', views.tags_list, name='tags_page_list'),
    re_path(r'^tags/(?P<tag_id>[0-9]+)/edit/$', views.tag_edit, name='tag_edit'),
    path('tags/<int:pk>/delete/', views.TagDelete.as_view(), name='tag-delete'),
    re_path(r'^tags/(?P<tag_id>[0-9]+)/history/$', views.tag_history, name='tag_history'),
    re_path(r'^tags/(?P<tag_id>[0-9]+)/history/(?P<page_number>[0-9]+)/$', views.tag_history, name='tag_history'),
    re_path(r'^tags/(?P<tag_id>[0-9]+)/revision_difference/$', views.tag_revision_diff, name='tag_revision_diff'),

    path('tag_implications', views.ImplicationListView.as_view(), name='implication-list'),
    path('tag_implications/<int:pk>/', views.ImplicationDetailView.as_view(), name='implication-detail'),

    re_path(r'^tag_implication_request/$', views.implication_create, name='implication_create'),

    re_path(r'^tag_implications/(?P<implication_id>[0-9]+)/approve/$', views.implication_approve, name='implication_approve'),
    re_path(r'^tag_implications/(?P<implication_id>[0-9]+)/disapprove/$', views.implication_disapprove, name='implication_disapprove'),
    
    re_path(r'^tag_search/$', views.tag_search, name='tag_search'),

    re_path(r'^profile/(?P<account_slug>[\w-]+)/$', booru.account.views.profile, name='profile'),
    re_path(r'^profile/(?P<account_slug>[\w-]+)/delete$', booru.account.views.DeleteAccountView.as_view(), name='profile_delete'),

    re_path(r'^gallery/list/$', views.gallery_list, name='gallery'),
    re_path(r'^gallery/list/(?P<page_number>[0-9]+)/$', views.gallery_list, name='gallery_list'),
    re_path(r'^gallery/new/$', views.gallery_create, name='gallery_create'),
    re_path(r'^gallery/(?P<gallery_id>[0-9]+)/$', views.gallery_detail, name='gallery_detail'),
    re_path(r'^gallery/(?P<gallery_id>[0-9]+)/edit$', views.gallery_edit, name='gallery_edit'),
    re_path(r'^gallery/(?P<gallery_id>[0-9]+)/history/$', views.gallery_history, name='gallery_history'),
    re_path(r'^gallery/(?P<gallery_id>[0-9]+)/history/(?P<page_number>[0-9]+)/$', views.gallery_history, name='gallery_history_page'),
    re_path(r'^staff_page/$', views.staff_page, name='staff_page'),
    re_path(r'^staff_page/mass_rename$', views.staff_mass_rename, name='staff_mass_rename'),
    re_path(r'^staff_page/configuration$', views.SiteConfigurationView.as_view(), name='staff_site_configuration'),
    re_path(r'^staff_page/block$', views.StaffBanUser.as_view(), name='staff_block'),
    path('comment/<int:pk>/toggle_view', booru.core.views.StaffCommentToggleHiddenView.as_view(), name='comment-toggle-view'),
    path('inbox', views.message_box, name='dm_inbox'),
    path('inbox/new', views.create_dm, name='create_dm'),
    path('inbox/send', views.send_dm, name='send_dm'),
    # path('inbox/delete/<int:pk>', views.delete_message, name='delete_message'),
    # path('blocks/add/<int:pk>', views.add_dm_block, name='add_dm_block'),
    # path('blocks/remove/<int:pk>', views.remove_dm_block, name='remove_dm_block')
    path('forum', views.forum_listing, name='forum_listing'),
    path('activity', views.activity_listing, name='activity_listing'),
    path('newsite', views.new_index, name='new_homepage'),
    path('404', views.throw_404, name='not_found'),
    path('banned', views.show_ban_page, name='ban_page'),
    path('json_test', views.json_test, name='json_test'),
    path('ajax_login', views.ajax_login, name='ajax_login'),
    path('robots.txt', views.show_robots_file, name='robots'),
]

devproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path, re_path

from booru.models import Post
from booru.sitemaps import PostSitemap, TagsSitemap, PostListSitemap

sitemaps = {
    'post_list': PostListSitemap,
    'posts': PostSitemap,
    'tags': TagsSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^', include('booru.urls')),
    re_path(r'^', include('booru.core.urls')),
    re_path(r'^account/', include('booru.account.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booru/core/models.py
from django.db import models


class BannedHash(models.Model):
    content = models.CharField(max_length=32, blank=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)
    creator = models.ForeignKey('account.Account', null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.content

    class Meta:
        verbose_name_plural = 'Banned hashes (MD5)'
        permissions = (
            ("ban_hashes", "Can ban hashes of media"),
        )


class PostFlag(models.Model):
    post = models.ForeignKey('booru.Post', on_delete=models.CASCADE)
    reason = models.CharField(max_length=500, blank=False)
    creator = models.ForeignKey('account.Account', null=True, on_delete=models.SET_NULL)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
    update_timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)

    PENDING = 0
    RESOLVED = 1
    STATUS_CHOICES = (
        (PENDING, 'Pending'),
        (RESOLVED, 'Resolved'),
    )
    status = models.IntegerField(
        choices=STATUS_CHOICES,
        default=PENDING,
    )

    def __str__(self):
        return "{} -> {}".format(self.id, self.post)

    class Meta:
        verbose_name_plural = 'Post flags'

booru/core/forms.py
from django import forms
from booru.core.models import BannedHash, PostFlag


class BannedHashCreateForm(forms.ModelForm):
    """Form for creating a BannedHash."""

    class Meta:
        model = BannedHash
        fields = ["content"]

    def __init__(self, *args, **kwargs):
        super(BannedHashCreateForm, self).__init__(*args, **kwargs)
        self.fields['content'].widget = forms.TextInput(attrs={'class': 'form-control'})


class PostFlagCreateForm(forms.ModelForm):
    """Form for creating a flag for post."""

    class Meta:
        model = PostFlag
        fields = ['reason']

    def __init__(self, *args, **kwargs):
        super(PostFlagCreateForm, self).__init__(*args, **kwargs)
        self.fields['reason'].widget = forms.Textarea(attrs={'class': 'form-control', 'cols': 15})

booru/account/views.py
from django.contrib.auth import REDIRECT_FIELD_NAME, authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.decorators import method_decorator
from django.utils.http import is_safe_url
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import FormView, RedirectView, TemplateView
from rolepermissions.checkers import has_permission, has_role
from rolepermissions.roles import assign_role, clear_roles

from booru.account.decorators import user_is_not_blocked
from booru.models import Comment, Post

from .forms import (StaffUserGroupForm, UserAuthenticationForm,
                    UserRegisterForm, UserSettingsForm)
from .models import Account


class LoginView(FormView):
    """
    Provides the ability to login as a user with a username and password
    """
    success_url = '/post/list'
    form_class = UserAuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = "booru/account/login.html"

    @method_decorator(sensitive_post_parameters('password'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect('/post/list')

        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(LoginView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        auth_login(self.request, form.get_user())

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(LoginView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, allowed_hosts=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


class LogoutView(RedirectView):
    """
    Provides users the ability to logout
    """
    url = '/account/login/'

    def get(self, request, *args, **kwargs):
        auth_logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)


class RegisterView(FormView):
    """
    Provides the ability to a visitor to register as new user
    with an username, an email and a password
    """
    success_url = '/post/list'
    form_class = UserRegisterForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = "booru/account/register.html"

    @method_decorator(sensitive_post_parameters('password1'))
    @method_decorator(sensitive_post_parameters('password2'))
    @method_decorator(csrf_protect)
    @method_decorator(never_cache)
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return HttpResponseRedirect('/post/list')

        # Sets a test cookie to make sure the user has cookies enabled
        request.session.set_test_cookie()

        return super(RegisterView, self).dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        form.save()

        username = form.cleaned_data.get('username')
        raw_password = form.cleaned_data.get('password1')

        user = authenticate(username=username, password=raw_password)
        auth_login(self.request, user)

        # If the test cookie worked, go ahead and
        # delete it since its no longer needed
        if self.request.session.test_cookie_worked():
            self.request.session.delete_test_cookie()

        return super(RegisterView, self).form_valid(form)

    def get_success_url(self):
        redirect_to = self.request.GET.get(self.redirect_field_name)
        if not is_safe_url(url=redirect_to, allowed_hosts=self.request.get_host()):
            redirect_to = self.success_url
        return redirect_to


@user_is_not_blocked
def profile(request, account_slug):
    account = get_object_or_404(Account.objects.active(), slug=account_slug)

    can_modify_profile = (request.user == account or has_permission(request.user, "modify_profile"))

    user_group_form = StaffUserGroupForm(request.POST or None, request.FILES or None)

    if request.user.is_authenticated:
        if user_group_form.is_valid() and has_permission(request.user, "change_user_group"):
            group = user_group_form.cleaned_data['group']
            clear_roles(account)
            assign_role(account, group)

            if group in ['administrator', 'moderator', 'janitor']:
                account.is_staff = True
                account.save()

        has_comment_priv = request.user.has_priv("can_comment")
        can_change_group = has_permission(request.user, "change_user_group")
    else:
        has_comment_priv = False
        can_change_group = False

    if request.method == "POST":
        newCommentTextarea = request.POST.get("newCommentTextarea")
        aboutUserTextarea = request.POST.get("aboutUserTextarea")

        if not request.user.is_authenticated:
            return redirect('account:login')
        elif newCommentTextarea and has_comment_priv:  # Comment creating
            comment_content = newCommentTextarea
            Comment.objects.create(content=comment_content, author=request.user, content_object=account)
            return redirect('booru:profile', account_slug=account.slug)
        elif aboutUserTextarea and can_modify_profile:  # About myself editing
            account.about = aboutUserTextarea
            account.save()
            return redirect('booru:profile', account_slug=account.slug)

    # TODO: I don't remember if I can safely pass account as a parameter to the render.
    favorites = Post.objects.filter(favorites__account=account)[:5]

    context = {
        'account': account,
        'recent_favorites': favorites,
        'recent_uploads': account.get_posts().not_deleted().order_by('-id'),
        'deleted_posts': account.get_posts().deleted(),
        'can_modify_profile': request.user.is_authenticated and can_modify_profile,
        'can_comment': has_comment_priv,
        'user_group_form': user_group_form,
        'can_change_group': can_change_group
    }

    return render(request, 'booru/account/profile.html', context)


class SettingsView(FormView):
    """
    Provides the ability to a visitor to register as new user
    with an username, an email and a password.
    """
    success_url = '.'
    form_class = UserSettingsForm
    redirect_field_name = REDIRECT_FIELD_NAME
    template_name = "booru/account/settings.html"

    def get_initial(self):
        """
        Returns the initial data to use for forms on this view.
        """
        initial = super().get_initial()
        account = self.request.user

        initial['safe_only'] = account.safe_only
        initial['show_comments'] = account.show_comments
        # TODO: implement the tag blacklist
        # initial['tag_blacklist'] = account.tag_blacklist

        return initial

    def form_valid(self, form):
        account = self.request.user

        account.safe_only = form.cleaned_data.get('safe_only')
        account.show_comments = form.cleaned_data.get('show_comments')
        account.tag_blacklist = form.cleaned_data.get('tag_blacklist')
        account.save()

        return super().form_valid(form)

    @user_is_not_blocked
    @method_decorator(csrf_protect)
    def dispatch(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('account:login')

        return super().dispatch(request, *args, **kwargs)


class DeleteAccountView(RedirectView):
    """
    Provides users the ability to logout
    """
    url = '/account/logout'

    def get(self, request, *args, **kwargs):
        if kwargs['account_slug'] == self.request.user.slug:
            self.request.user.anonymize()

        return super(DeleteAccountView, self).get(request, *args, **kwargs)

booru/templates/booru/account/login.html
{% extends 'booru/base.html' %}

{% block css %}
    {% load staticfiles %}
{% endblock %}

{% block scripts %}
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col">
            <h1>Login</h1>

            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="form-group row">
                    <label for="{{ form.username.auto_id }}" class="col-1 col-form-label">{{ form.username.label }}</label>
                    
                    <div class="col-4">
                        {{form.username}}
                        <span class="custom-file-control"></span>
                    </div>

                    {% if form.username.errors %}
                    <div class="col-md-offset-2 col-8 text-danger small">
                        {{form.username.errors}}
                    </div>
                    {% endif %}
                </div>

                <div class="form-group row">
                    <label for="{{ form.password.auto_id }}" class="col-1 col-form-label">{{ form.password.label }}</label>
                    
                    <div class="col-4">
                        {{form.password}}
                        <span class="custom-file-control"></span>
                    </div>

                    {% if not form.username.errors and form.errors %}
                    <div class="col-md-offset-2 col-8 text-danger small">
                        The given password is incorrect.
                    </div>
                    {% endif %}
                </div>

                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

booru/templates/booru/account/profile.html
{% extends 'booru/base.html' %}

{% block css %}
    {% load staticfiles %}
{% endblock %}

{% block scripts %}
    <script src="{% static 'booru/account/js/profile.js' %}"></script>
{% endblock %}

{% block body %}
    {% load humanize %}
    {% load permission_tags %}
    {% load crispy_forms_tags %}
    <div class="row">
        <div class="col col-md-3 mb-5">
            <div class="col text-center">
                <h4 class="mb-0">{{account.username}}</h4>
            </div>

            <div class="col text-center">
                <!-- ROLES -->
                <span class="badge badge-danger rounded pill text-capitalize">{{account.groups.all.first}}</span>
            </div>

            {% if account.avatar %}
                <div class="col">
                    <a href="{% url 'booru:post_detail' account.avatar.id %}"><img class="mx-auto d-block" src='{{account.avatar.preview.url}}'></a>
                </div>
            {% endif %}

            <table class="table table-sm mt-3">
                <tbody>
                    <tr>
                        <th scope="row">Joined</th>
                        <td title="{{account.date_joined}}"><strong>{{account.date_joined|date:"M d, Y"}}</strong>
                            <br> <small>{{account.date_joined|naturaltime}}</small> </td>
                    </tr>
                    <tr>
                        <th scope="row">Posts</th>
                        <td>{{recent_uploads.count}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Deleted Posts</th>
                        <td>{{deleted_posts.count}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Favorites</th>
                        <td>{{account.get_favorites_count}}</td>
                    </tr>
                    <tr>
                        <th scope="row">Comments</th>
                        <td>{{account.get_comments_count}}</td>
                    </tr>
                    <tr>
                        <!-- TODO add proper values to these cells -->
                        <th scope="row">Tag Edits</th>
                        <td>-</td>
                    </tr>
                    <tr>
                        <th scope="row">Note Edits</th>
                        <td>-</td>
                    </tr>
                    <tr>
                        <th scope="row">Forum Posts</th>
                        <td>-</td>
                    </tr>
                    <tr>
                        <th scope="row">Record +</th>
                        <td>-</td>
                    </tr>
                </tbody>
            </table>
            {% if user|can:'change_user_group' %}
            <div>
                <h4>Admin tools</h4>
                <form method="post" enctype="multipart/x-www-form-urlencoded">
                    {% csrf_token %}
                    {{ user_group_form |crispy }}
                    <button type="submit" class="btn btn-primary">Set</button>
                </form>
            </div>
            {% endif %}
        </div>
        <div class="col col-md-6 mb-5">
            <div class="col">
                <h3>Recent Favorites</h3>
                {% if recent_favorites %}
                <table class="table table-sm mt-3">
                    <tbody>
                        {% for post in recent_favorites|slice:":5" %}
                        <tr>
                            <td><a href="{% url 'booru:post_detail' post.id %}"><img src='{{post.preview.url}}' style="width:100px;"></a></td>
                            <td class="align-middle">Favorited #<a href="{% url 'booru:post_detail' post.id %}">{{post.id}}</a> <span title="{{post.timestamp}}">on {{post.timestamp|date:"M d, Y \a\t\ f A"}}</span></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p class="text-muted">{{account.username}} has not added any favorites yet!</p>
                {% endif %}
            </div>
            <div class="col mt-4">
                <h3>Recent Uploads</h3>

                {% if recent_uploads %}
                <table class="table table-sm mt-3">
                    <tbody>
                        {% for post in recent_uploads %}
                        <tr>
                            <td><a href="{% url 'booru:post_detail' post.id %}"><img src='{{post.preview.url}}' style="width:100px;"></a></td>
                            <td class="align-middle">Uploaded #<a href="{% url 'booru:post_detail' post.id %}">{{post.id}}</a><span title="{{post.timestamp}}"> on {{post.timestamp|date:"M d, Y \a\t\ f A"}}</span></td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                <a href="#" class="btn btn-primary btn-rounded text-center float-right">View All of {{account.username}}'s Uploads</a>
                {% else %}
                    <p class="text-muted">{{account.username}} has not uploaded anything yet!</p>
                {% endif %}
            </div>
        </div>
        <div class="col col-md-3">
            <h3>
                About myself
                {% if user|can:'modify_profile' %}
                <a class="float-right" id="edit_about" href="#"><i class="fas fa-pencil-alt"></i></a>
                {% endif %}
            </h3>

            {% load markdown_deux_tags %}

            <div id="about-data">
                {% if account.about %}
                {{ account.about|markdown }}
                {% else %}
                    <p class="text-muted">This user has no bio.</p>
                {% endif %}
            </div>

            <div class="form-group" id="about-edit" style="display: none;">
                <form method="post" action="." enctype="multipart/form-data">
                    {% csrf_token %}
                    <textarea class="form-control" id="aboutUserTextarea" name="aboutUserTextarea" rows="4">{{account.about}}</textarea>
                    <button type="submit" id="send_about" class="btn btn-md btn-primary float-right mt-1">Save changes</button>
                </form>
            </div>
        </div>
    </div>
    {% if request.user.show_comments %}
    <div class="row">
        <div id="comment-section" class="mt-3 mb-3 col offset-2">
            <h3>Comments</h3>
            <div id="comments" class="row">
                {% for comment in account.comments.all %}
                <div id="comment-{{comment.id}}" class="comment col-10 border comment-border pt-3 pb-3 mb-2">
                    <div class="row">
                        <div class="comment col">
                            <div class="row">
                                    <span class="col">
                                        {% if comment.author.is_deleted %}
                                        <h5>{{comment.author.get_name}}</h5>
                                        {% else %}
                                        <h5><a href="{{comment.author.get_absolute_url}}">{{comment.author.get_name}}</a></h5>
                                        {% endif %}
                                    </span>
                                </div>
                            <div class="row">
                                <span class="col text-muted">
                                    {{comment.timestamp|naturaltime}}
                                </span>
                            </div>
                            <div class="row">
                                <span class="col">
                                    <small>Score: {{comment.get_score}}</small>
                                </span>
                            </div>
                            {% if user|can:'manage_comments' %}
                        {% endif %}
                        </div>
                        <div class="comment col-9">
                            {% load markdown_deux_tags %}
                            {{comment.content|markdown}}
                        </div>
                    </div>
                    {% if user|can:'manage_comments' %}
                        <div class="row">
                            <div class="col offset-3">
                                {% if comment.is_hidden %}
                                <a href="{% url 'booru:comment-toggle-view' comment.pk %}" class="btn btn-sm btn-success">
                                     <i class="far fa-eye"></i> Show
                                </a>
                                {% else %}
                                <a href="{% url 'booru:comment-toggle-view' comment.pk %}" class="btn btn-sm btn-danger">
                                    <i class="far fa-eye-slash"></i> Hide
                                </a>
                                {% endif %}
                            </div>
                        </div>
                        {% endif %}
                </div>
                {% endfor %}
            </div>
            <div id="comment-create-form" class="row mt-3">
                <form class="col-10" method="post" action="." enctype="multipart/form-data">
                    {% if not user.is_authenticated %}
                    <fieldset disabled>
                    {% endif %}

                        {% csrf_token %}
                        <div class="form-group">
                            {% if not user.is_authenticated %}
                            <label for="newCommentTextarea" class="text-muted">New comment (Login to comment)</label>
                            {% else %}
                            <label for="newCommentTextarea">New comment</label>
                            {% endif %}
                            <textarea class="form-control" id="newCommentTextarea" name="newCommentTextarea" rows="3" {% if not can_comment %}placeholder="This account cannot comment currently." disabled{% endif %}></textarea>
                        </div>
                        {% if can_comment %}
                        <button type="submit" id="sendComment" class="btn btn-sm btn-primary">Create comment</button>
                        {% endif %}
                    {% if not user.is_authenticated %}
                    </fieldset>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    {% endif %}
{% endblock %}